CREATE TABLE  MURUN.ADDRESS (
     ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
       STREET VARCHAR(20) NOT NULL,
       STATE VARCHAR(2) NOT NULL,
     ZIPCODE VARCHAR(5) NOT NULL,
       PRIMARY KEY (`ID`) USING BTREE
        
     ) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

GRANT  ALL on MURUN.ADDRESS  to public;

INSERT INTO MURUN.ADDRESS (id, STREET, STATE, ZIP) VALUES(1, 'STREET-1', 'STATE-1', 'ZIP-1' );


INSERT INTO MURUN.ADDRESS (STREET, STATE, ZIPCODE) VALUES('STREET-2', 'CA', '90402' );

INSERT INTO MURUN.ADDRESS (STREET, STATE, ZIPCODE) VALUES('STREET-3', 'CA', '90402' );
INSERT INTO MURUN.ADDRESS (STREET, STATE, ZIPCODE) VALUES('STREET-4', 'CA', '90404' );
INSERT INTO MURUN.ADDRESS (STREET, STATE, ZIPCODE) VALUES('STREET-5', 'CA', '90404' );
INSERT INTO MURUN.ADDRESS (STREET, STATE, ZIPCODE) VALUES('STREET-6', 'CA', '90404' );


commit;

 select * from MURUN.ADDRESS 